### ISSUE TITLE
Can't submit Gentx on agorictest-13

### ISSUE THREAD

**Issue by aditya-manit** [Agoric/testnet-notes#10]
## Command on which error occurs
```
ag-chain-cosmos gentx $myKey 50000000ubld --output-document=gentx.json \
  --chain-id=$chainName \
  --keyring-dir=$HOME/.ag-cosmos-helper \
  --moniker="$myMoniker" \
  --website=<your-node-website> \
  --details=<your-node-details> \
  --commission-rate="0.10" \
  --commission-max-rate="0.20" \
  --commission-max-change-rate="0.01" \
  --min-self-delegation="1"
  ```
## Error
 Facing
`Error: failed to fetch <key-name> from the keyring: <key-name>.info: key not found`

## How to reproduce

Just try to follow the instructions for creating gentx on agorictest-13 [Instructions](https://github.com/Agoric/agoric-sdk/wiki/Creating-a-gentx)

## Hack used to fix

 Added the key in `.ag-chain-comos` folder as well, by recovering it from the mnemonic
 `ag-chain-cosmos keys add <key-name> --recover`
 
 ## Side note
 Now both `.ag-chain-cosmos` and `.ag-cosmos-helper` have a file `<key-name>.info`
 Earlier I think only `.ag-cosmos-helper` used to have it

**Comment by dckc** [comment]
## Work-around: downgrade to agorictest-12 release

I've seen this work-around reported a number of times.

**Comment by sjors-lemniscap** [comment]
I can confirm that downgrading to `agorictest-12` works for generating the gentx. 

Another workaround which I can confirm is using the following on `agorictest-13`:
`ag-chain-cosmos keys add <your-new-key-name> --recover`
instead of
`ag-cosmos-helper keys add <your-new-key-name> --recover`

What would be good to know is whether this bug might interfere with the scheduled launch, hence my suggestion to sanity check the release by the Agoric team.

**Comment by humantraffic** [comment]
I had the same problem, and also solved it by recover

**Comment by michaelfig** [comment]
I've opened a PR against the Cosmos SDK to fix this: cosmos/cosmos-sdk#9574.

The relevant Agoric SDK PR is at Agoric/agoric-sdk#3401

**Comment by pkrasam** [comment]
Due to this current issue, I generated and submitted `gentx.json` via portal using the older release version `agorictest-12`

**Comment by michaelfig** [comment]
> Due to this current issue, I generated and submitted `gentx.json` via portal using the older release version `agorictest-12`

That's fine.  You should be good to go.
