### ISSUE TITLE
repeated unexplained jailing in stress test

### ISSUE THREAD

**Issue by aditya-manit** [Agoric/testnet-notes#12]
# Repeated jailing during stress test  (╯°□°）╯︵ ┻━┻

Most of the participants kept getting jailed repeatedly during stress test.

# Possible Reasons
Here are possible reasons that people suggested with my rationale why it can or can't be the reasons

## Reasons 1: Low number of peers
- Some people reported [low number of peers](https://discord.com/channels/585576150827532298/819073555446759444/860444938096082956)
- It can't be that because after [I shared my peer in the chat](https://discord.com/channels/585576150827532298/819073555446759444/860482776397774848) I had 43 peers and was still getting jailed.

## Reason 2: Low Hardware Specs
- Some people [reported](https://discord.com/channels/585576150827532298/819073555446759444/860448209214111764) high cpu utilization and load than usual
- It can't be that, here is my conversation with one of the fellow participant

![screenshot-discord com-2021 07 17-21_22_11](https://user-images.githubusercontent.com/40714633/126042618-b4ad48f4-4572-4d7f-bf7c-b9c2b8be890e.png)

He was running double the specs mentioned in the guide and still was getting jailed.

## Reason 3: Two Different Consensus Heights
- At some time during testnet I noticed - there were [two different consensus heights](https://discord.com/channels/585576150827532298/819073555446759444/860441546402824203) - the comparison was between my node and the public rpc node -  both were moving and both were having `catching_up` as `false`
- It certaintly could be the reason that some of us were running on a different consensus, but the larger consensus height could be different and therefore minority of us were kept getting jailed. That's just my hypothesis
-----
1. I am curious what is the real cause was and how one can avoid it during mainnet during high traffic.
2. Also one thing is for sure whatever the cause was - it was beyond validator's control - that's just because, whoever was getting jailed tried there best and it was like more than 30 peoples, so something bigger might be at play 😛  - just an assumption

PS: Have added relevant chat links

**Comment by dckc** [comment]
@michaelfig @warner any thoughts?

cc @rowgraus

**Comment by michaelfig** [comment]
Hi @aditya-manit, thanks for this clear report.  I still don't have a clear understanding of what the reason for this repeated jailing could be.

I have not ruled out Reason 2 (insufficient hardware capacity).  Even 2 times the guide's recommendation (which was just my back-of-an-envelope estimate) may be too little.

Is there any way that your Reason 3 could be correct?

> * At some time during testnet I noticed - there were [two different consensus heights](https://discord.com/channels/585576150827532298/819073555446759444/860441546402824203) - the comparison was between my node and the public rpc node -  both were moving and both were having `catching` up as `false`
> * It certaintly could be the reason that some of us were running on a different consensus, but the larger consensus height could be different and therefore minority of us were kept getting jailed. That's just my hypothesis

I don't see how the minority could have consensus, because I would expect that your peer would refuse to make progress if it noticed that 1/3+ of the validator delegations had gone missing.  So, network partition should not be possible.  I may be wrong, though, so any more details about how this could happen would be appreciated.

**Comment by aditya-manit** [comment]
Hi @michaelfig Tbh, I am not sure how network will behave in this case, I mean if there are two consensus will it take 1/3 of delegation of the entire network into account or 1/3 of the individual network running at different heights, no idea on this.

The major argument here is if there are two heights and both are moving either one of them should have `catching_up` as `false`
