### ISSUE TITLE
gentx submitted after deadline

### ISSUE THREAD

**Issue by shaimo** [Agoric/testnet-notes#18]
Don't know if still relevant to submit it here:

{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"","identity":"","website":"octopos.app","security_contact":"","details":""},"commission":{"rate":"0.100000000000000000","max_rate":"1.000000000000000000","max_change_rate":"0.100000000000000000"},"min_self_delegation":"1","delegator_address":"agoric1jhhn6clpcpuvtg5gha88c3mhun5fzhrk5vg9p9","validator_address":"agoricvaloper1jhhn6clpcpuvtg5gha88c3mhun5fzhrky5mvay","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"mX9pl0dB0Eyawi72Z4BXKc3lfjWSWw8qVimTIAuAKXQ="},"value":{"denom":"ubld","amount":"50000000"}}],"memo":"ee39b9ea93b6cb07826ddbe35f46a2d8027e513d@62.171.148.56:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AlWf5W+VudTf+gIlJ+WceQB5RRT86REdAwfsYfy4WFDM"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":["CI3If6WeiEUL+2uAWZ5tWRszsXhSgsRWoTOrii/48B1NMRYnyiwrFX39m8ybxm8GnT2B3XHMm+jnLx1Cfa6tHA=="]}

**Comment by dckc** [comment]
I suppose I wasn't clear... what I meant was: if some issue beyond your control makes it difficult for you to submit correctly on time, go ahead and submit _something_ on time; that something should point to the issue that is beyond your control, which should be filed here.

I didn't mean that you should submit your gentx here. You should submit it thru the portal as usual.

It's hard for me to tell whether you already did; the moniker in the above gentx is empty. In order to connect your validator to your rewards account in the portal, we need a moniker.

**Comment by shaimo** [comment]
Thanks. I did submit it already on the portal. Moniker is Octopos. Strange that it was empty. I guess some variable wasn’t set. Should I resubmit?

**Comment by dckc** [comment]
yes, you should resubmit.

**Comment by shaimo** [comment]
Just done (didn't have permission to edit the old one, so I submitted a new one). Here it is again too, just in case...

{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"Octopos","identity":"","website":"octopos.app","security_contact":"","details":""},"commission":{"rate":"0.100000000000000000","max_rate":"1.000000000000000000","max_change_rate":"0.100000000000000000"},"min_self_delegation":"1","delegator_address":"agoric1jhhn6clpcpuvtg5gha88c3mhun5fzhrk5vg9p9","validator_address":"agoricvaloper1jhhn6clpcpuvtg5gha88c3mhun5fzhrky5mvay","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"mX9pl0dB0Eyawi72Z4BXKc3lfjWSWw8qVimTIAuAKXQ="},"value":{"denom":"ubld","amount":"50000000"}}],"memo":"ee39b9ea93b6cb07826ddbe35f46a2d8027e513d@62.171.148.56:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AlWf5W+VudTf+gIlJ+WceQB5RRT86REdAwfsYfy4WFDM"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""}},"signatures":["xaQkizDo29MDbMl0s6IVuKDbzso0bbC+jnSL1Mq0IjJUBIXx83uJpQM5u8twVWmIHjhagJXvz8QdHNi7WV4CzQ=="]}

**Comment by dckc** [comment]
bingo. thanks.
