### ISSUE TITLE
RPC nodes unreliable? chain-cosmos-sdk: Error: post failed: Post "http://...:26657/": EOF

### ISSUE THREAD

**Issue by dckc** [Agoric/testnet-notes#30]
**Describe the bug**

We're seeing a log of EOF / RESET from RPC nodes.

**Additional context**

possibly a dup of #26

see also: [NEW: Conduct performance analysis](https://validate.agoric.com/9e7e00e1f3c34ce5b7e80903f9f85ed7)

**Comment by dckc** [comment]
@dtribble points out there's a single lock across RPC queries, JS exection, etc.

This is the PR that created the ABCI locking situation  https://github.com/cosmos/cosmos-sdk/pull/8549
https://github.com/cosmos/cosmos-sdk/issues/8591

https://github.com/osmosis-labs/osmosis/issues/414 is the osmosis issue that references all the other ones.

**Comment by yelllowsin** [comment]
I am getting this same issue, running updated RPC agorictest-17.3:

`2021-08-24T17:52:50.688Z chain-cosmos-sdk: Error: post failed: Post "http://161.97.168.77:26657/": EOF`

and randomly the error changes to this:

`2021-08-24T17:52:57.663Z chain-cosmos-sdk: Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = egress not found: key not found`

My agoric address has both BLD and RUN tokens:

https://testnet.explorer.agoric.net/account/agoric1xsh9py32qyk3lvtavxsgpjh7jry6c7xh6g2lqm

**Comment by dckc** [comment]
your client retries and continues to make progress, right, @yelllowsin ?

**Comment by yelllowsin** [comment]
> your client retries and continues to make progress, right, @yelllowsin ?

it keeps retrying yeh, but fails every time with these errors I mentioned. Here is a longer log:

[log1.log](https://github.com/Agoric/testnet-notes/files/7041801/log1.log)

**Comment by michaelfig** [comment]
https://github.com/Agoric/agoric-sdk/issues/3763#issuecomment-913044941 points to my analysis of Tendermint locking, and a perf test of a simple change to allow parallelism again.

**Comment by michaelfig** [comment]
I've verified that this failure is a consequence of a stalled query due to the RPC locking.  The Agoric/agoric-sdk#3805 PR fixes this.

Marking as closed for now.
