### ISSUE TITLE
Treasury : No assets due to no fees, hidden fee UX

### ISSUE THREAD

**Issue by kalpatech-team** [Agoric/testnet-notes#32]
**Describe the bug**
Treasury doesn't connect to wallet even after 1h

For some reason it can't connect to RPC node ... i replaced with my IP in connections.json
Everything it's whitelisted between the servers so we can exclude the firewall issues

**Logs when refresh wallet page**
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:07.860Z web: GET / 304 - - 2.820 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:07.995Z web: 172.22.0.1:45848[10]: client closed
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.006Z web: 172.22.0.1:45832[9]: client closed
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.019Z web: GET /main.js 304 - - 2.526 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.317Z web: GET /git-revision.txt 304 - - 1.675 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.448Z web: 172.22.0.1:46010[11]: new WebSocket /private/repl?accessToken=mizVG4V4oVv_SYcXwEO3LOCebz1016iuglfvNrE8rvriyhhy7V2fa1Thc1Js0gXT
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.565Z web: GET /wallet/?accessToken=mizVG4V4oVv_SYcXwEO3LOCebz1016iuglfvNrE8rvriyhhy7V2fa1Thc1Js0gXT 304 - - 2.272 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.566Z web: GET /package.json 304 - - 2.360 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.743Z web: POST /private/repl?accessToken=mizVG4V4oVv_SYcXwEO3LOCebz1016iuglfvNrE8rvriyhhy7V2fa1Thc1Js0gXT 200 39 - 50.081 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.824Z web: GET /wallet/ 304 - - 1.261 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:08.977Z web: POST /private/repl?accessToken=mizVG4V4oVv_SYcXwEO3LOCebz1016iuglfvNrE8rvriyhhy7V2fa1Thc1Js0gXT 200 22 - 53.855 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:09.055Z web: GET /wallet/build/smelte.css 304 - - 2.162 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:09.056Z web: GET /wallet/build/bundle.css 304 - - 2.402 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:09.282Z web: GET /wallet/build/bundle.js 304 - - 1.080 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:09.440Z web: GET /wallet/logo.png 304 - - 3.583 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:26:09.558Z web: 172.22.0.1:46026[12]: new WebSocket /private/captp?accessToken=mizVG4V4oVv_SYcXwEO3LOCebz1016iuglfvNrE8rvriyhhy7V2fa1Thc1Js0gXT

**Logs when refresh treasury page**
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:27:42.012Z web: GET /wallet-bridge.html?suggestedDappPetname=Treasury 304 - - 2.091 ms
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:27:42.407Z web: 172.22.0.1:46054[13]: new WebSocket /private/wallet-bridge?suggestedDappPetname=Treasury
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:27:42.915Z outbound: invoking deliverator; 1 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:27:43.415Z chain-cosmos-sdk: delivering to chain (trips=10) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [
d5073e73d139_ag-solo_ag-solo_1 |   [
d5073e73d139_ag-solo_ag-solo_1 |     222,
d5073e73d139_ag-solo_ag-solo_1 |     '222:207:deliver:ro+253020:lookup:rp-254;["uiConfig","Treasury"]'
d5073e73d139_ag-solo_ag-solo_1 |   ]
d5073e73d139_ag-solo_ag-solo_1 | ] 207
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:27:58.748Z chain-cosmos-sdk: Error: post failed: Post "http://173.249.40.87:26657": EOF
d5073e73d139_ag-solo_ag-solo_1 | Usage:
d5073e73d139_ag-solo_ag-solo_1 |   ag-chain-cosmos tx swingset deliver [json string] [flags]
d5073e73d139_ag-solo_ag-solo_1 | 
d5073e73d139_ag-solo_ag-solo_1 | Flags:
d5073e73d139_ag-solo_ag-solo_1 |   -a, --account-number uint      The account number of the signing account (offline mode only)
d5073e73d139_ag-solo_ag-solo_1 |   -b, --broadcast-mode string    Transaction broadcasting mode (sync|async|block) (default "sync")
d5073e73d139_ag-solo_ag-solo_1 |       --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it
d5073e73d139_ag-solo_ag-solo_1 |       --fee-account string       Fee account pays fees for the transaction instead of deducting from the signer
d5073e73d139_ag-solo_ag-solo_1 |       --fees string              Fees to pay along with transaction; eg: 10uatom
d5073e73d139_ag-solo_ag-solo_1 |       --from string              Name or address of private key with which to sign
d5073e73d139_ag-solo_ag-solo_1 |       --gas string               gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically (default 200000)
d5073e73d139_ag-solo_ag-solo_1 |       --gas-adjustment float     adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
d5073e73d139_ag-solo_ag-solo_1 |       --gas-prices string        Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
d5073e73d139_ag-solo_ag-solo_1 |       --generate-only            Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase is not accessible)
d5073e73d139_ag-solo_ag-solo_1 |   -h, --help                     help for deliver
d5073e73d139_ag-solo_ag-solo_1 |       --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
d5073e73d139_ag-solo_ag-solo_1 |       --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
d5073e73d139_ag-solo_ag-solo_1 |       --ledger                   Use a connected Ledger device
d5073e73d139_ag-solo_ag-solo_1 |       --node string              <host>:<port> to tendermint rpc interface for this chain (default "tcp://localhost:26657")
d5073e73d139_ag-solo_ag-solo_1 |       --note string              Note to add a description to the transaction (previously --memo)
d5073e73d139_ag-solo_ag-solo_1 |       --offline                  Offline mode (does not allow any online functionality
d5073e73d139_ag-solo_ag-solo_1 |   -o, --output string            Output format (text|json) (default "json")
d5073e73d139_ag-solo_ag-solo_1 |   -s, --sequence uint            The sequence number of the signing account (offline mode only)
d5073e73d139_ag-solo_ag-solo_1 |       --sign-mode string         Choose sign mode (direct|amino-json), this is an advanced feature
d5073e73d139_ag-solo_ag-solo_1 |       --timeout-height uint      Set a block timeout height to prevent the tx from being committed past a certain height
d5073e73d139_ag-solo_ag-solo_1 |   -y, --yes                      Skip tx broadcasting prompt confirmation
d5073e73d139_ag-solo_ag-solo_1 | 
d5073e73d139_ag-solo_ag-solo_1 | Global Flags:
d5073e73d139_ag-solo_ag-solo_1 |       --chain-id string     The network chain ID
d5073e73d139_ag-solo_ag-solo_1 |       --home string         directory for config and data (default "/root/.ag-cosmos-helper")
d5073e73d139_ag-solo_ag-solo_1 |       --log_format string   The logging format (json|plain) (default "plain")
d5073e73d139_ag-solo_ag-solo_1 |       --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
d5073e73d139_ag-solo_ag-solo_1 |       --trace               print out full stack trace on errors
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:27:58.749Z chain-cosmos-sdk: Error sending (SyntaxError#4)
d5073e73d139_ag-solo_ag-solo_1 | SyntaxError#4: Unexpected end of JSON input
d5073e73d139_ag-solo_ag-solo_1 | 
d5073e73d139_ag-solo_ag-solo_1 |   at JSON.parse (<anonymous>)
d5073e73d139_ag-solo_ag-solo_1 |   at sendFromMessagePool (packages/solo/src/chain-cosmos-sdk.js:484:28)
d5073e73d139_ag-solo_ag-solo_1 |   at async recurseEachSend (packages/solo/src/chain-cosmos-sdk.js:556:5)
d5073e73d139_ag-solo_ag-solo_1 | 
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:27:59.252Z chain-cosmos-sdk: delivering to chain (trips=11) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [
d5073e73d139_ag-solo_ag-solo_1 |   [
d5073e73d139_ag-solo_ag-solo_1 |     222,
d5073e73d139_ag-solo_ag-solo_1 |     '222:207:deliver:ro+253020:lookup:rp-254;["uiConfig","Treasury"]'
d5073e73d139_ag-solo_ag-solo_1 |   ]
d5073e73d139_ag-solo_ag-solo_1 | ] 207
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:27:59.459Z chain-cosmos-sdk: gas estimate: 48415
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:11.107Z outbound: invoking deliverator; 0 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:11.535Z outbound: invoking deliverator; 1 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:11.600Z outbound: invoking deliverator; 1 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:12.036Z chain-cosmos-sdk: delivering to chain (trips=12) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [
d5073e73d139_ag-solo_ag-solo_1 |   [ 223, '223:208:deliver:ro+253022:getValue:rp-255;["381205908"]' ],
d5073e73d139_ag-solo_ag-solo_1 |   [ 224, '224:208:deliver:ro+253022:getValue:rp-256;["1456154132"]' ]
d5073e73d139_ag-solo_ag-solo_1 | ] 208
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:36.215Z chain-cosmos-sdk: Error: post failed: Post "http://173.249.40.87:26657": EOF
d5073e73d139_ag-solo_ag-solo_1 | Usage:
d5073e73d139_ag-solo_ag-solo_1 |   ag-chain-cosmos tx swingset deliver [json string] [flags]
d5073e73d139_ag-solo_ag-solo_1 | 
d5073e73d139_ag-solo_ag-solo_1 | Flags:
d5073e73d139_ag-solo_ag-solo_1 |   -a, --account-number uint      The account number of the signing account (offline mode only)
d5073e73d139_ag-solo_ag-solo_1 |   -b, --broadcast-mode string    Transaction broadcasting mode (sync|async|block) (default "sync")
d5073e73d139_ag-solo_ag-solo_1 |       --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it
d5073e73d139_ag-solo_ag-solo_1 |       --fee-account string       Fee account pays fees for the transaction instead of deducting from the signer
d5073e73d139_ag-solo_ag-solo_1 |       --fees string              Fees to pay along with transaction; eg: 10uatom
d5073e73d139_ag-solo_ag-solo_1 |       --from string              Name or address of private key with which to sign
d5073e73d139_ag-solo_ag-solo_1 |       --gas string               gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically (default 200000)
d5073e73d139_ag-solo_ag-solo_1 |       --gas-adjustment float     adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
d5073e73d139_ag-solo_ag-solo_1 |       --gas-prices string        Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
d5073e73d139_ag-solo_ag-solo_1 |       --generate-only            Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase is not accessible)
d5073e73d139_ag-solo_ag-solo_1 |   -h, --help                     help for deliver
d5073e73d139_ag-solo_ag-solo_1 |       --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
d5073e73d139_ag-solo_ag-solo_1 |       --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
d5073e73d139_ag-solo_ag-solo_1 |       --ledger                   Use a connected Ledger device
d5073e73d139_ag-solo_ag-solo_1 |       --node string              <host>:<port> to tendermint rpc interface for this chain (default "tcp://localhost:26657")
d5073e73d139_ag-solo_ag-solo_1 |       --note string              Note to add a description to the transaction (previously --memo)
d5073e73d139_ag-solo_ag-solo_1 |       --offline                  Offline mode (does not allow any online functionality
d5073e73d139_ag-solo_ag-solo_1 |   -o, --output string            Output format (text|json) (default "json")
d5073e73d139_ag-solo_ag-solo_1 |   -s, --sequence uint            The sequence number of the signing account (offline mode only)
d5073e73d139_ag-solo_ag-solo_1 |       --sign-mode string         Choose sign mode (direct|amino-json), this is an advanced feature
d5073e73d139_ag-solo_ag-solo_1 |       --timeout-height uint      Set a block timeout height to prevent the tx from being committed past a certain height
d5073e73d139_ag-solo_ag-solo_1 |   -y, --yes                      Skip tx broadcasting prompt confirmation
d5073e73d139_ag-solo_ag-solo_1 | 
d5073e73d139_ag-solo_ag-solo_1 | Global Flags:
d5073e73d139_ag-solo_ag-solo_1 |       --chain-id string     The network chain ID
d5073e73d139_ag-solo_ag-solo_1 |       --home string         directory for config and data (default "/root/.ag-cosmos-helper")
d5073e73d139_ag-solo_ag-solo_1 |       --log_format string   The logging format (json|plain) (default "plain")
d5073e73d139_ag-solo_ag-solo_1 |       --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
d5073e73d139_ag-solo_ag-solo_1 |       --trace               print out full stack trace on errors
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:36.215Z chain-cosmos-sdk: Error sending (SyntaxError#5)
d5073e73d139_ag-solo_ag-solo_1 | SyntaxError#5: Unexpected end of JSON input
d5073e73d139_ag-solo_ag-solo_1 | 
d5073e73d139_ag-solo_ag-solo_1 |   at JSON.parse (<anonymous>)
d5073e73d139_ag-solo_ag-solo_1 |   at sendFromMessagePool (packages/solo/src/chain-cosmos-sdk.js:484:28)
d5073e73d139_ag-solo_ag-solo_1 |   at async recurseEachSend (packages/solo/src/chain-cosmos-sdk.js:556:5)
d5073e73d139_ag-solo_ag-solo_1 | 
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:36.716Z chain-cosmos-sdk: delivering to chain (trips=13) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [
d5073e73d139_ag-solo_ag-solo_1 |   [ 223, '223:208:deliver:ro+253022:getValue:rp-255;["381205908"]' ],
d5073e73d139_ag-solo_ag-solo_1 |   [ 224, '224:208:deliver:ro+253022:getValue:rp-256;["1456154132"]' ]
d5073e73d139_ag-solo_ag-solo_1 | ] 208
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:36.864Z chain-cosmos-sdk: gas estimate: 48484
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:51.192Z outbound: invoking deliverator; 0 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:51.396Z outbound: invoking deliverator; 1 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:51.470Z outbound: invoking deliverator; 1 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:51.524Z outbound: invoking deliverator; 1 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:51.604Z outbound: invoking deliverator; 1 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:51.689Z outbound: invoking deliverator; 1 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:51.897Z chain-cosmos-sdk: delivering to chain (trips=14) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [
d5073e73d139_ag-solo_ag-solo_1 |   [
d5073e73d139_ag-solo_ag-solo_1 |     225,
d5073e73d139_ag-solo_ag-solo_1 |     '225:210:deliver:ro+253032:getPublicFacet:rp-257:ro+253076;[{"@qclass":"slot","iface":"Alleged: InstanceHandle","index":0}]'
d5073e73d139_ag-solo_ag-solo_1 |   ],
d5073e73d139_ag-solo_ag-solo_1 |   [
d5073e73d139_ag-solo_ag-solo_1 |     226,
d5073e73d139_ag-solo_ag-solo_1 |     '226:210:deliver:ro+253032:getTerms:rp-258:ro+253076;[{"@qclass":"slot","iface":"Alleged: InstanceHandle","index":0}]'
d5073e73d139_ag-solo_ag-solo_1 |   ],
d5073e73d139_ag-solo_ag-solo_1 |   [ 227, '227:210:deliver:rp-257:getCollaterals:rp-259;[]' ],
d5073e73d139_ag-solo_ag-solo_1 |   [
d5073e73d139_ag-solo_ag-solo_1 |     228,
d5073e73d139_ag-solo_ag-solo_1 |     '228:210:deliver:ro+253032:getPublicFacet:rp-260:ro+253077;[{"@qclass":"slot","iface":"Alleged: InstanceHandle","index":0}]'
d5073e73d139_ag-solo_ag-solo_1 |   ],
d5073e73d139_ag-solo_ag-solo_1 |   [
d5073e73d139_ag-solo_ag-solo_1 |     229,
d5073e73d139_ag-solo_ag-solo_1 |     '229:210:deliver:ro+253032:getTerms:rp-261:ro+253077;[{"@qclass":"slot","iface":"Alleged: InstanceHandle","index":0}]'
d5073e73d139_ag-solo_ag-solo_1 |   ]
d5073e73d139_ag-solo_ag-solo_1 | ] 210
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:28:52.049Z chain-cosmos-sdk: gas estimate: 49036
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:29:46.038Z SwingSet: vat: v2: Temporary logging of sent error [RangeError: -50 is negative]
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:29:46.125Z SwingSet: vat: v2: Temporary logging of sent error [RangeError: -50 is negative]
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:29:46.166Z SwingSet: vat: v2: Temporary logging of sent error [RangeError: -50 is negative]
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:29:46.258Z outbound: invoking deliverator; 0 new messages for 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:29:46.759Z chain-cosmos-sdk: delivering to chain (trips=15) 80280a37099594d8be7323f30a7c757535bd014c9f5198303b3f866d6656e41a [] 215
d5073e73d139_ag-solo_ag-solo_1 | 2021-08-25T15:29:46.896Z chain-cosmos-sdk: gas estimate: 48323

<img width="585" alt="Screenshot 2021-08-25 at 18 33 52" src="https://user-images.githubusercontent.com/60131093/130820618-519e7e79-9db3-4726-8d40-f6cc9539cd2c.png">
<img width="473" alt="Screenshot 2021-08-25 at 18 34 09" src="https://user-images.githubusercontent.com/60131093/130820634-5bd8a99e-0d02-416e-98bf-b302f28c5d56.png">

**Comment by rowgraus** [comment]
@dckc I will close this unless there is an issue here other than fee purse not having RUN.

**Comment by dckc** [comment]
The fee purse not having RUN is due to an unusable / undiscoverable interface, evidently. Is there some other issue that represents plans to address that?

**Comment by katelynsills** [comment]
> The fee purse not having RUN is due to an unusable / undiscoverable interface, evidently. Is there some other issue that represents plans to address that?

Yes: https://github.com/Agoric/agoric-sdk/issues/3780

**Comment by dckc** [comment]
OK, let's use that to track this going forward.

"The error should direct the deployer’s attention to their low RUN balance." suggests a scope more narrow than the treasury web UX, but I trust that will work out in due course.
