### ISSUE TITLE
Node won't restart

### ISSUE THREAD

**Issue by chris-remus** [Agoric/testnet-notes#37]
Error - 

```Aug 26 17:14:54 cflow-agoric-tn-01 ag-chain-cosmos[2233165]: Cannot initialize Controller ExitCode: v10:zoe exited: I/O error```

See full logs -

https://hackmd.io/yjJrpQGfT1eoqmasn1I6kw?view

**Comment by dckc** [comment]
Thanks for the report; this `Bad address` error in the zoe vat looks like a duplicate of #33 .
