### ISSUE TITLE
Node crash

### ISSUE THREAD

**Issue by niocris** [Agoric/testnet-notes#38]
![agoric bag error](https://user-images.githubusercontent.com/34162722/131210782-7d4a287b-06d9-4052-b3e5-4d3621474344.png)
Due to the frequent jailing, it was decided to urgently switch to another server, synchronization took 4.5 days, and then this error, due to which some tasks were skipped.

The following quests were skipped:
 - AMM Trade Part 1: Make a trade on the AMM and get charged a fee
 - AMM Trade Part 2: Find the crank number of the offer you made on the AMM trade in your slog file
 - NEW: Conduct performance analysis

**Comment by dckc** [comment]
Thanks for noting that this is a dup of #33.

I trust you will still fill out the knack portal for the tasks above, citing either this issue or #33 .

**Comment by dckc** [comment]
Meanwhile, it seems to me that you did collect at least a little bit of performance analysis information - you noted frequent jailing; if you find a moment to elaborate on that, please do share that.
