### ISSUE TITLE
Multiple transaction ID for a swap: why?

### ISSUE THREAD

**Issue by Gotogu** [Agoric/testnet-notes#4]
A single swap is leading to multiple transaction id. 
Approximately 10 "Eventual Send" and 2 "Acknowledgement".

![image](https://user-images.githubusercontent.com/52324283/117538534-f1ec0000-b006-11eb-8bb5-b29ac9bd78ac.png)

https://github.com/Agoric/testnet-notes/issues/3#issuecomment-835337883

**Comment by Tartuffo** [comment]
Working as intended.
