### ISSUE TITLE
mainnet0 snapshot sharing (Use at your own risk.)

### ISSUE THREAD

**Issue by dckc** [Agoric/testnet-notes#42]
**Note**: moving to https://github.com/Agoric/validator-profiles/wiki/Snapshots

These links were shared in discord. **Use at your own risk.**
Feel free to add more in further comments.

> Danil Ushakov: My Agoric mainnet daily snapshot service
> https://snapshots.stake2.me/agoric/
> How to use:
> https://github.com/k0kk0k/cosmos-snapshots-doc/blob/main/agoric.md
>
> Maybe it will help someone to quickly restore the node in case of unforeseen circumstances

https://github.com/c29r3/cosmos-snapshots/blob/main/Agoric.md

**Comment by Tartuffo** [comment]
Thanks for the snapshot!

**Comment by Phantom1605** [comment]
Here is the state sync snapshot with the guide "how to use is". 
https://github.com/Phantom1605/State-Sync-Snapshots#agoric

It seems to me that for purposes such as running a **validator node** or a **sentry node**, `state sync` is better than full data snapshot, as it will save a lot of disk space.

**Comment by dckc** [comment]
> ...`state sync` is better ...

Yes, here's hoping we get there: https://github.com/Agoric/agoric-sdk/issues/3769

**Comment by dckc** [comment]
Let's use https://github.com/Agoric/validator-profiles/wiki/Snapshots for this going forward.
