### ISSUE TITLE
Treasury not finding Purses in Wallet due to mis-configured faucet

### ISSUE THREAD

**Issue by 0xd18b** [Agoric/testnet-notes#5]
Context: https://discordapp.com/channels/585576150827532298/819073555446759444/841120528831479838

I can consistently reproduce in a Brave browser. Looks like a handful of others are in the same boat and have tried in other browsers:

* https://discordapp.com/channels/585576150827532298/819073555446759444/841333425407131658
* https://discordapp.com/channels/585576150827532298/819073555446759444/841021183750176808
* https://discordapp.com/channels/585576150827532298/819073555446759444/841024489676341330
* https://discordapp.com/channels/585576150827532298/819073555446759444/841088969164718121

To reproduce:
* `docker-compose up` on this docker compose: https://testnet.agoric.net/docker-compose.yml
* I get tokens from testnet-faucet: https://discordapp.com/channels/585576150827532298/824414814230020156/840444663294590997 (68 ATOM, 0 BLD, 51 LINK, 5 RUN (and counting), 1323 USDC, ...)
* I open https://treasury.agoric.app/ 
* (I turn off Brave Shields in both Treasury and App)
* I see `To continue, please approve the Treasury Dapp in your wallet.`
* I bounce over to my wallet and see the invitation for the Treasury Dapp drop in
* I toggle to "Enabled"
* I bounce back over to the Treasury and see what looks to be a successful connection, but it says `No assets are available to use as collateral.`

Wallet, after I Enabled the Treasury Dapp:
![image](https://user-images.githubusercontent.com/70670395/117693532-1fae8180-b18c-11eb-9f32-436aaf6680ea.png)

Treasury, after I Enabled the Treasury Dapp:
![image](https://user-images.githubusercontent.com/70670395/117693576-2c32da00-b18c-11eb-8de0-a440c64bdf0b.png)

Two Notes:
When running: `ag-cosmos-helper query bank balances agoric1...` for my address, I can see a balance:

```
balances:
- amount: "19872489"
  denom: urun
pagination:
  next_key: null
  total: "0"
```

So I definitely have `RUN`.

I can also toggle `Enabled` on and off and see the Treasury Dapp react each time. So two-way communication is happening successfully.

**Comment by dckc** [comment]
The faucet was still pointed at `agorictest-11`. Now that the faucet is on `agorictest-12`, taping the faucet gives assets that show up in the wallet.
