### ISSUE TITLE
could not create directory ".../.ag-cosmos-helper": file exists

### ISSUE THREAD

**Issue by dckc** [Agoric/testnet-notes#6]
What are some likely causes of this panic? How do I get past it?

```
$ ag-cosmos-helper query staking validators
panic: could not create directory "/home/connolly/.ag-cosmos-helper": mkdir /home/connolly/.ag-cosmos-helper: file exists
```

cc @michaelfig

**Comment by michaelfig** [comment]
> What are some likely causes of this panic? How do I get past it?

What does the following show you?

```sh
ls -al /home/connolly/.ag-cosmos-helper
id
```

**Comment by dckc** [comment]
ah. `ls -al /home/connolly/.ag-cosmos-helper` shows a symlink to a directory that isn't there (I moved it the other day).

Thanks.

_I'm going to leave this open for a bit until I'm confident that it doesn't merit more documentation._
